### PR TITLE
more pythonic opensubtitle

### PR DESCRIPTION
**Pull request by FurkanSalih**

### CODE REVIEW

**Comment by furkanvarol** [comment]
have you checked this with flake8?

**Comment by FurkanSalih** [comment]
Yeap

**Comment by furkanvarol** [comment]
👍

**Comment by kubudi** [comment]
lgtm

**Comment by FurkanSalih** [comment]
Time to merge then. I don't have write access :)

**Comment by kubudi** [comment]
I gave your suku

**Pull request merged**
